// Pricing plans shared by the Services, Pricing and Donna AI pages.

export const SERVICE_PLANS = [
  {
    id: 'web',
    title: 'Website & Web App Development',
    subtitle: 'Modern digital experiences and portals designed to convert visitors into customers.',
    deepLink: '/services/web-development',
    plans: [
      {
        name: 'Starter Website',
        subtitle: 'Emerging brands & local businesses',
        price: '₹15,000',
        features: [
          'Up to 5 responsive pages',
          'Mobile-first responsive design',
          'Modern UI & typography',
          'Contact & inquiry forms',
          'WhatsApp business integration',
          'Basic SEO meta setup & indexing',
          'Production deployment',
          '1 revision cycle',
        ],
        popular: false,
      },
      {
        name: 'Business Website',
        subtitle: 'Growing companies seeking conversions',
        price: '₹30,000',
        features: [
          'Up to 10 custom pages',
          'Custom UI/UX & micro-interactions',
          'CMS integration for dynamic content',
          'Full technical SEO optimization',
          'Analytics & conversion tracking',
          'Lead capture & autoresponder flow',
          'Zero-downtime deployment',
          'Multiple revision cycles',
        ],
        popular: true,
      },
      {
        name: 'Enterprise / Portal',
        subtitle: 'Custom digital platforms & dashboards',
        price: '₹50,000+',
        features: [
          'Custom web application logic',
          'User authentication & client portal',
          'Database integration & storage',
          'Custom admin management console',
          'Third-party API integrations',
          'Payment gateways (Stripe/Razorpay)',
          'Priority post-launch support',
        ],
        popular: false,
      },
    ],
  },
  {
    id: 'apps',
    title: 'Mobile App Development',
    subtitle: 'Cross-platform iOS and Android applications with native performance.',
    deepLink: '/services/mobile-app-development',
    plans: [
      {
        name: 'App Starter',
        subtitle: 'MVP & prototype validation',
        price: '₹60,000',
        features: [
          'Android & iOS cross-platform',
          '5–8 core user screens',
          'User registration & authentication',
          'Cloud database integration',
          'Push notification alerts',
          'App Store & Play Store deployment',
        ],
        popular: false,
      },
      {
        name: 'App Business',
        subtitle: 'Production consumer / business app',
        price: '₹1,25,000',
        features: [
          'Custom UI/UX interface architecture',
          'Multi-role permissions & profiles',
          'Custom REST API backend & database',
          'Web admin management portal',
          'Payment gateway & in-app purchases',
          'Real-time data synchronization',
          'Full store submission approval',
        ],
        popular: true,
      },
      {
        name: 'App Enterprise',
        subtitle: 'High-scale complex mobile systems',
        price: '₹2,50,000+',
        features: [
          'Offline-first synchronization architecture',
          'Real-time chat & location tracking',
          'Complex enterprise workflows',
          'Automated testing & CI/CD pipeline',
          'Security audit & token encryption',
          'Dedicated SLA support lead',
        ],
        popular: false,
      },
    ],
  },
  {
    id: 'software',
    title: 'Custom Business Software & ERPs',
    subtitle: 'Tailored platforms engineered specifically around your company’s operational workflows.',
    deepLink: '/services/custom-software',
    plans: [
      {
        name: 'Software Starter',
        subtitle: 'Focused workflow automation',
        price: '₹75,000',
        features: [
          'Custom internal software tool',
          'Custom relational database schema',
          'Core operational CRUD flows & forms',
          'Role-based staff authentication',
          'CSV / Excel / PDF data export',
          'Secure cloud deployment & training',
        ],
        popular: false,
      },
      {
        name: 'Software Business (ERP)',
        subtitle: 'Comprehensive ERP, CRM or billing system',
        price: '₹1,50,000',
        features: [
          'Full operational business platform',
          'Multi-warehouse inventory ledger',
          'POS checkout & automated GST invoicing',
          'Granular staff permission matrix',
          'Automated email/SMS triggers',
          'Third-party software & API sync',
        ],
        popular: true,
      },
      {
        name: 'Software Enterprise',
        subtitle: 'High-throughput operational backbone',
        price: '₹3,00,000+',
        features: [
          'Bespoke enterprise architecture',
          'High-volume transactional ledgers',
          'Real-time business analytics & telemetry',
          'Legacy data migration & audit trails',
          'Multi-tenant cloud architecture',
          'Custom SLAs & continuous engineering',
        ],
        popular: false,
      },
    ],
  },
  {
    id: 'ai',
    title: 'AI Solutions & Telephony Voice',
    subtitle: 'Practical AI systems that automate routine knowledge work and customer phone interactions.',
    deepLink: '/services/ai-development',
    plans: [
      {
        name: 'AI Starter',
        subtitle: 'Knowledge retrieval & FAQ bot',
        price: '₹25,000',
        features: [
          'Custom knowledge base indexing (RAG)',
          'Intelligent web chat assistant',
          'Prompt engineering & brand safeguards',
          'Lead capture & email routing',
          'Analytics & conversation history',
        ],
        popular: false,
      },
      {
        name: 'AI Business',
        subtitle: 'Omnichannel multi-agent pipelines',
        price: '₹50,000',
        features: [
          'Omnichannel agents (Web, WhatsApp, Email)',
          'CRM & database live tool calling',
          'Automated calendar scheduling bot',
          'Document & invoice PDF parsing',
          'Human-in-the-loop escalation triggers',
        ],
        popular: true,
      },
      {
        name: 'AI Enterprise (Donna AI)',
        subtitle: 'Telephony voice agents & custom models',
        price: 'Custom',
        features: [
          'Telephony voice integration pipeline',
          'Donna AI custom business deployment',
          'Private LLM / VPC dedicated deployment',
          'Custom fine-tuned domain models',
          'Enterprise SLAs & data compliance',
        ],
        popular: false,
      },
    ],
  },
  {
    id: 'automation',
    title: 'Business Process Automation',
    subtitle: 'Connect your applications, databases, and pipelines to eliminate repetitive manual work.',
    deepLink: '/services/ai-automation',
    plans: [
      {
        name: 'Automation Starter',
        subtitle: 'Core application connectors',
        price: '₹15,000',
        features: [
          'Connect 2 to 3 core business tools',
          'Automated form-to-CRM pipelines',
          'Instant WhatsApp / SMS notifications',
          'Error logging & alert routing',
          'Deployment & validation',
        ],
        popular: false,
      },
      {
        name: 'Automation Business',
        subtitle: 'End-to-end customer workflow',
        price: '₹35,000',
        features: [
          'Multi-tool pipeline (CRM, Billing, DB)',
          'Automated customer onboarding sequence',
          'Payment reconciliation triggers',
          'Custom webhook & API transformation',
          'Full audit logging & retry engine',
        ],
        popular: true,
      },
      {
        name: 'Automation Enterprise',
        subtitle: 'Mission-critical orchestration',
        price: '₹75,000+',
        features: [
          'High-throughput message queue pipelines',
          'Legacy database synchronization',
          'Custom microservices & endpoints',
          'Zero-data-loss failover architecture',
          'Continuous monitoring & SLA',
        ],
        popular: false,
      },
    ],
  },
  {
    id: 'maintenance',
    title: 'Maintenance, SLAs & DevOps',
    subtitle: 'Long-term reliability, security hardening, backups, and regular feature updates.',
    deepLink: '/pricing',
    plans: [
      {
        name: 'Essential Support',
        subtitle: 'Routine maintenance & uptime',
        price: '₹3,000',
        period: '/ mo',
        features: [
          'Bug fixes & security patches',
          'Framework & dependency updates',
          'Automated daily cloud backups',
          '24/7 uptime & SSL monitoring',
          'Email support within 24 hours',
        ],
        popular: false,
      },
      {
        name: 'Business Support',
        subtitle: 'Proactive engineering & upgrades',
        price: '₹7,500',
        period: '/ mo',
        features: [
          'Priority email & chat engineering support',
          'Continuous performance & latency audits',
          'Minor UI & feature improvements',
          'Database index & query optimization',
          'Monthly infrastructure health report',
        ],
        popular: true,
      },
      {
        name: 'Premium SLA Support',
        subtitle: 'Mission-critical operational lead',
        price: '₹15,000',
        period: '/ mo',
        features: [
          'Dedicated technical account lead',
          'Rapid priority development queue',
          'Guaranteed 1-hour critical response SLA',
          'Real-time alert escalation & failover',
          'On-demand architecture consulting',
        ],
        popular: false,
      },
    ],
  },
];

export const DONNA_PLANS = [
  {
    name: 'Donna Starter',
    price: '₹4,999',
    period: '/ month',
    setup: 'Starting from ₹10,000 setup',
    description: 'Ideal for solo clinics, local salons, and small service practices.',
    features: [
      'Dedicated inbound phone line setup',
      'Standard business hours answering',
      'FAQ & location information handling',
      'Basic customer contact capture',
      'SMS & email call summaries',
    ],
    popular: false,
  },
  {
    name: 'Donna Business',
    price: '₹9,999',
    period: '/ month',
    setup: 'Starting from ₹20,000 setup',
    description: 'Engineered for busy dental clinics, consultancies, and active sales teams.',
    features: [
      'Higher concurrent call capacity',
      'Direct calendar appointment booking',
      'Intelligent lead qualification workflow',
      'Warm transfer to staff mobile numbers',
      'CRM & database integration (HubSpot/Sheets)',
      'Detailed audio recordings & transcripts',
    ],
    popular: true,
  },
  {
    name: 'Donna Enterprise',
    price: '₹19,999',
    period: '/ month',
    setup: 'Custom architecture setup',
    description: 'For multi-location practices, hospital chains, and high-volume operations.',
    features: [
      'Multi-agent concurrent telephony lines',
      'Custom voice clone & localized accents',
      'Custom internal ERP & database API tools',
      'Strict SLA response guarantees',
      'Dedicated support engineer',
    ],
    popular: false,
  },
];
